name: Deploy Laravel + React (Staging & Live)

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            if [ "${{ github.ref_name }}" = "staging" ]; then
              cd /home/u548741633/domains/erp.wishery.tech/public_html/staging
              git pull origin staging
            else
              cd /home/u548741633/domains/erp.wishery.tech/public_html
              git pull origin main
            fi

            echo "🧹 Clearing old build..."
            rm -rf public/build

            echo "📦 Installing dependencies..."
            npm install

            echo "⚙️ Building React..."
            npm run build

            echo "📁 Checking build..."
            ls -l public/build

            composer install --no-dev --optimize-autoloader

            php artisan optimize:clear
            php artisan migrate --force

            php artisan config:cache
